# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

PROJECT_ROOT = Path(SPECPATH).resolve().parent

_binaries = []
if sys.platform == "linux":
    _expat_path = Path(sys.prefix) / "lib" / "libexpat.so.1"
    if _expat_path.is_file():
        _binaries.append((str(_expat_path), "."))

a = Analysis(
    [str(PROJECT_ROOT / "gui" / "gui" / "main.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=_binaries,
    datas=[
        (str(PROJECT_ROOT / "gui" / "locales"), "locales"),
        (str(PROJECT_ROOT / "gui" / "gui" / "infer_task_params.json"), "gui"),
    ],
    hiddenimports=[
        "ultralytics",
        "ultralytics.nn",
        "ultralytics.nn.modules",
        "ultralytics.nn.tasks",
        "ultralytics.data",
        "ultralytics.data.build",
        "ultralytics.utils",
        "ultralytics.utils.checks",
        "ultralytics.utils.downloads",
        "ultralytics.engine",
        "ultralytics.engine.model",
        "ultralytics.engine.results",
        "torch",
        "cv2",
        "numpy",
        "yaml",
        "matplotlib",
        "matplotlib.backends.backend_agg",
        "PIL",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtWidgets",
        "tools.dataset_tools.create_empty_labels",
        "tools.dataset_tools.split_train_val.split_random_with_labels",
        "tools.dataset_tools.split_train_val_test.split_random_with_labels",
        "tools.dataset_tools.split_train_val.split_every_5th_with_labels",
        "tools.dataset_tools.split_images_only.split_random_images_only",
        "tools.dataset_tools.split_images_only.split_every_5th_images_only",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "torchaudio",
        "nvidia",
        "nvidia.cublas",
        "nvidia.cudnn",
        "nvidia.cufft",
        "nvidia.curand",
        "nvidia.cusolver",
        "nvidia.cusparse",
        "nvidia.nccl",
        "nvidia.nvtx",
        "nvidia.cuda_runtime",
        "triton",
        "triton.language",
        "triton.runtime",
        "PySide6.QtWebEngine",
        "PySide6.QtWebEngineCore",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebChannel",
        "PySide6.QtMultimedia",
        "PySide6.QtMultimediaWidgets",
        "PySide6.QtBluetooth",
        "PySide6.QtNfc",
        "PySide6.QtSensors",
        "PySide6.QtSerialPort",
        "PySide6.QtPositioning",
        "PySide6.QtLocation",
        "PySide6.QtRemoteObjects",
        "PySide6.QtTextToSpeech",
        "polars",
        "polars_runtime_32",
        "torch.test",
        "torch.testing",
        "torch.distributed",
        "torch.distributed._composable",
        "torch.distributed._shard",
        "torch.distributed._tensor",
        "torch.distributed.algorithms",
        "torch.distributed.checkpoint",
        "torch.distributed.fsdp",
        "torch.distributed.optim",
        "torch.distributed.pipeline",
        "torch.distributed.rpc",
        "torch.distributed.tensor",
        "scipy",
        "pandas",
        "tcl",
        "tkinter",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="YoloLab",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(PROJECT_ROOT / "packaging" / "assets" / "icon.ico")
        if sys.platform == "win32" else str(PROJECT_ROOT / "packaging" / "assets" / "icon.png"),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="YoloLab",
)
